version: '3.8'

services:
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcanderson-api-app
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      NODE_ENV: production
